[package]
name = "resize_png"
version = "0.1.0"
authors = ["shanlihou <shanlihou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
argparse = "*"
glium = "*"
